<?php

require_once dirname(__FILE__) . '/../../../../../../app/coreLib/ui/form/validation/ValidatorFactory.php';
require_once dirname(__FILE__) . '/../../../../../../app/coreLib/ui/form/validation/EmailValidator.php';
require_once dirname(__FILE__) . '/../../../../../../app/coreLib/ui/form/validation/RuleInterface.php';
require_once dirname(__FILE__) . '/../../../../../../app/coreLib/ui/form/validation/EmailRule.php';

/**
 * Test class for ValidatorFactory.
 * Generated by PHPUnit on 2012-05-29 at 16:31:00.
 */
class ValidatorFactoryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ValidatorFactory
     */
    protected $object;
    protected $emailObj;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ValidatorFactory;
        $this->emailObj = $this->object->create('EmailValidator');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ValidatorFactory::create
     * @todo Implement testCreate().
     */
    public function testCreate() {
        $errorMsg = 'This is not an email address';
        $this->emailObj->setEmailValid(null, $errorMsg);
        $result = $this->emailObj->validate("Not_an_email");
        $this->assertEquals($result[0], $errorMsg);
    }

}

?>
