<?php

require_once dirname(__FILE__) . '/../../../../app/coreLib/acl/Authentication.php';

/**
 * Test class for Authentication.
 * Generated by PHPUnit on 2012-05-02 at 14:40:07.
 */
class AuthenticationTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Authentication
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Authentication;
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Authentication::isLogin
     * @todo Implement testIsLogin().
     */
    public function testIsLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Authentication::getSignInAction
     * @todo Implement testGetSignInAction().
     */
    public function testGetSignInAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Authentication::getLoginController
     * @todo Implement testGetLoginController().
     */
    public function testGetLoginController() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Authentication::getLoginAction
     * @todo Implement testGetLoginAction().
     */
    public function testGetLoginAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Authentication::getLoginErrorAction
     * @todo Implement testGetLoginErrorAction().
     */
    public function testGetLoginErrorAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Authentication::getRegisterAction
     * @todo Implement testGetRegisterAction().
     */
    public function testGetRegisterAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Authentication::getLoginExcludeActions
     * @todo Implement testGetLoginExcludeActions().
     */
    public function testGetLoginExcludeActions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Authentication::getAllAllows
     * @todo Implement testGetAllAllows().
     */
    public function testGetAllAllows() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
