<?php

require_once dirname(__FILE__) . '/../../../../../../app/coreLib/ui/UIComponent.php';
require_once dirname(__FILE__) . '/../../../../../../app/coreLib/ui/form/components/AbstractFormElement.php';

/**
 * Test class for UIComponent.
 * Generated by PHPUnit on 2012-05-02 at 13:43:55.
 */
class AbstractFormElementTest extends PHPUnit_Framework_TestCase {

    /**
     * @var UIComponent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AbstractFormElement();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    /**
     * Generated from @assert (1, 1) == 2.
     */
    public function testGetId()
    {
        $id = 1;
        $this->object->setId($id);
        $this->assertEquals($id, $this->object->getId());
    }

    public function testRender()
    {
        $id = 1;
        $name = "test";
        $this->object->setId($id);
        $this->object->setName($name);
        $output = "<input id=\"1\" name=\"test\">";
        $this->assertEquals($output, $this->object->render());
    }
}

?>
