<?php

require_once dirname(__FILE__) . '/../../../config/lib/AclUtility.php';

/**
 * Test class for AclUtility.
 * Generated by PHPUnit on 2012-05-02 at 15:35:44.
 */
class AclUtilityTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AclUtility
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AclUtility;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AclUtility::getInstance
     * @todo Implement testGetInstance().
     */
    public function testGetInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AclUtility::loadXMLtoDOM
     * @todo Implement testLoadXMLtoDOM().
     */
    public function testLoadXMLtoDOM() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AclUtility::getAuthentications
     * @todo Implement testGetAuthentications().
     */
    public function testGetAuthentications() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AclUtility::getSuccessfulDispatch
     * @todo Implement testGetSuccessfulDispatch().
     */
    public function testGetSuccessfulDispatch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AclUtility::getDOMfromXML
     * @todo Implement testGetDOMfromXML().
     */
    public function testGetDOMfromXML() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AclUtility::getAllMapTblAttr
     * @todo Implement testGetAllMapTblAttr().
     */
    public function testGetAllMapTblAttr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AclUtility::getTableById
     * @todo Implement testGetTableById().
     */
    public function testGetTableById() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AclUtility::getMapTables
     * @todo Implement testGetMapTables().
     */
    public function testGetMapTables() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AclUtility::getMappingModuleTables
     * @todo Implement testGetMappingModuleTables().
     */
    public function testGetMappingModuleTables() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AclUtility::getTableIdByModule
     * @todo Implement testGetTableIdByModule().
     */
    public function testGetTableIdByModule() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AclUtility::getMappingFieldByTbl
     * @todo Implement testGetMappingFieldByTbl().
     */
    public function testGetMappingFieldByTbl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AclUtility::getRoleTypesByTbl
     * @todo Implement testGetRoleTypesByTbl().
     */
    public function testGetRoleTypesByTbl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AclUtility::getLoginedAccessRules
     * @todo Implement testGetLoginedAccessRules().
     */
    public function testGetLoginedAccessRules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AclUtility::getBrowseRules
     * @todo Implement testGetBrowseRules().
     */
    public function testGetBrowseRules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
