<?php

require_once dirname(__FILE__) . '/../../../../../../app/coreLib/ui/UIComponent.php';
require_once dirname(__FILE__) . '/../../../../../../app/coreLib/ui/form/components/ButtonElement.php';
require_once dirname(__FILE__) . '/../../../../../../app/coreLib/ui/form/components/InputType.php';

/**
 * Test class for UIComponent.
 * Generated by PHPUnit on 2012-05-02 at 13:43:55.
 */
class ButtonElementTest extends PHPUnit_Framework_TestCase {

    /**
     * @var UIComponent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ButtonElement(1);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    /**
     * Generated from @assert (1, 1) == 2.
     */
    public function testGetId()
    {
        $this->assertEquals(1, $this->object->getId());
    }

}

?>
